name: lg_arkanoid
description: LG Arkanoid multiplayer panoramic brick breaker controller for Liquid Galaxy.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^3.1.6
  flutter_secure_storage: ^10.3.1
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_tts: ^4.2.5
  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0
  google_fonts: ^6.1.0
  dartssh2: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/app_icon.png
    - assets/app_icon_transparent.png
    - assets/lg-logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
